//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoCobro.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Cliente
    {
        public B_Cliente()
        {
            this.B_Credito = new HashSet<B_Credito>();
        }
    
        public string IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public Nullable<int> IdInstitucion { get; set; }
    
        public virtual B_Institucion B_Institucion { get; set; }
        public virtual ICollection<B_Credito> B_Credito { get; set; }
    }
}
