//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoCobro.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Cuota
    {
        public int IdCuota { get; set; }
        public string IdEmpleado { get; set; }
        public int IdCredito { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> Intereses { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<bool> SePago { get; set; }
        public Nullable<decimal> Amortiza { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
    
        public virtual P_Empleado P_Empleado { get; set; }
    }
}
