//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoCobro.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Empleado
    {
        public P_Empleado()
        {
            this.P_Cuota = new HashSet<P_Cuota>();
        }
    
        public string IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
    
        public virtual ICollection<P_Cuota> P_Cuota { get; set; }
    }
}
